substitutions:
  name: "flexboss21"
  friendly_name: "FlexBOSS21"
  
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  on_boot:
    priority: -10
    then:
      - logger.log: "Normal boot"
    
# Throttle writing parameters to the internal flash memory to reduce ESP memory wear / degradation
preferences:
  flash_write_interval: 15min

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
    level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
    
ota:
  - platform: esphome
    password: !secret ota_key

# Configure UART / RS485
uart:
  id: rs485_uart
  tx_pin: GPIO17
  rx_pin: GPIO4
  baud_rate: 19200
  parity: NONE
  stop_bits: 1

# Configure Modbus (which runs on top of RS485)
modbus:
  id: mb
  uart_id: rs485_uart
  flow_control_pin:
    number: GPIO32   # DE + /RE tied together
    inverted: true

modbus_controller:
  - id: inverter_1
    address: 1        # inverter_1 Modbus address
    modbus_id: mb
    update_interval: 10s

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "AC Couple Enabled"
    register_type: read
    address: 77
    bitmask: 0x80 #(bit 8)

sensor:
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV1 Voltage"
    id: pv1_volt
    register_type: read
    address: 1
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV2 Voltage"
    id: pv2_volt
    register_type: read
    address: 2
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV3 Voltage"
    id: pv3_volt
    register_type: read
    address: 3
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery Voltage"
    id: vbat
    register_type: read
    address: 4
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery State of Charge"
    id: bat_soc
    address: 5
    register_type: read
    register_count: 1
    value_type: U_WORD
    unit_of_measurement: "%"
    device_class: battery
    accuracy_decimals: 0
    filters:
      - lambda: |-
          // EG4_cca-1C1212: reg 5 appears packed as 0xHHLL (HH=SOH, LL=SOC)
          int soc = (int(x) & 0xFF);
          // Optional safety clamp:
          //if (soc < 0) soc = 0;
          //if (soc > 100) soc = 100;
          return soc;

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery State of Health"
    id: bat_soh
    address: 5
    register_type: read
    register_count: 1
    value_type: U_WORD
    unit_of_measurement: "%"
    device_class: battery
    accuracy_decimals: 0
    filters:
      - lambda: |-
          // EG4_cca-1C1212: reg 5 appears packed as 0xHHLL (HH=SOH, LL=SOC)
          int soh = (int(x) >> 8);
          return soh;

# Ethernet Controller
ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  power_pin: GPIO5
  phy_addr: 1
  clk:
    pin: GPIO0
    mode: CLK_OUT

# This is here to ensure that the LED for 'Cloud' isn't half-lit
switch:
  - platform: gpio
    name: "LED13 Forced"
    pin:
      number: GPIO13
      mode: OUTPUT
      inverted: True
    restore_mode: ALWAYS_OFF
