substitutions:
  name: "flexboss21"
  friendly_name: "FlexBOSS21"
  
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  on_boot:
    priority: -10
    then:
      - logger.log: "Normal boot"
    
# Throttle writing parameters to the internal flash memory to reduce ESP memory wear / degradation
preferences:
  flash_write_interval: 15min

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
    level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
    
ota:
  - platform: esphome
    password: !secret ota_key

# Configure UART / RS485
uart:
  id: rs485_uart
  tx_pin: GPIO17
  rx_pin: GPIO4
  baud_rate: 19200
  parity: NONE
  stop_bits: 1

# Configure Modbus (which runs on top of RS485)
modbus:
  id: mb
  uart_id: rs485_uart
  flow_control_pin:
    number: GPIO32   # DE + /RE tied together
    inverted: true

modbus_controller:
  - id: inverter_1
    address: 1        # inverter_1 Modbus address
    modbus_id: mb
    update_interval: 10s

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "AC Couple Enabled"
    register_type: read
    address: 77
    bitmask: 0x80 #(bit 8)

sensor:
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV1 Voltage"
    id: Vpv1
    register_type: read
    address: 1
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV2 Voltage"
    id: Vpv2
    register_type: read
    address: 2
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV3 Voltage"
    id: Vpv3
    register_type: read
    address: 3
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery Voltage"
    id: Vbat
    register_type: read
    address: 4
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery State of Charge"
    id: SOC
    address: 5
    register_type: read
    #register_count: 1
    value_type: U_WORD
    unit_of_measurement: "%"
    device_class: battery
    accuracy_decimals: 0
    filters:
      - lambda: |-
          // EG4_cca-1C1212: reg 5 appears packed as 0xHHLL (HH=SOH, LL=SOC)
          int soc = (int(x) & 0xFF);
          // Optional safety clamp:
          //if (soc < 0) soc = 0;
          //if (soc > 100) soc = 100;
          return soc;

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery State of Health"
    id: SOH
    address: 5
    register_type: read
    #register_count: 1
    value_type: U_WORD
    unit_of_measurement: "%"
    device_class: battery
    accuracy_decimals: 0
    filters:
      - lambda: |-
          // EG4_cca-1C1212: reg 5 appears packed as 0xHHLL (HH=SOH, LL=SOC)
          int soh = (int(x) >> 8);
          return soh;
          
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV1 Power"
    id: Ppv1
    register_type: read
    address: 7
    unit_of_measurement: "W"
    value_type: U_WORD
 
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV2 Power"
    id: Ppv2
    register_type: read
    address: 8
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV3 Power"
    id: Ppv3
    register_type: read
    address: 9
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery Charge"
    id: Pcharge
    register_type: read
    address: 10
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery Discharge"
    id: Pdischarge
    register_type: read
    address: 11
    unit_of_measurement: "W"
    value_type: U_WORD

    # this is Phase R or Split Phase grid voltage
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Grid Voltage"
    id: VacR
    register_type: read
    #register_count: 4
    address: 12
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

    # this is Phase S grid voltage
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "S-Phase Grid Voltage"
    id: VacS
    register_type: read
    #register_count: 4
    address: 13
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

    # this is Phase T grid voltage
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "T-Phase Grid Voltage"
    id: VacT
    register_type: read
    #register_count: 4
    address: 14
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Grid Frequency"
    id: Fac
    register_type: read
    address: 15
    unit_of_measurement: "Hz"
    accuracy_decimals: 2
    value_type: U_WORD
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Inverter Grid port Output Power"
    id: Pinv
    register_type: read
    #register_count: 6
    address: 16
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "AC Charging Rectified Power"
    id: Prec
    register_type: read
    #register_count: 6
    address: 17
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Inverter Current RMS"
    id: IinvRMS
    register_type: read
    address: 18
    unit_of_measurement: Amps
    value_type: U_WORD
    entity_category: diagnostic
    filters: 
      - multiply: 0.01
    
# Ethernet Controller
ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  power_pin: GPIO5
  phy_addr: 1
  clk:
    pin: GPIO0
    mode: CLK_OUT

# This is here to ensure that the LED for 'Cloud' isn't half-lit
switch:
  - platform: gpio
    name: "LED13 Forced"
    pin:
      number: GPIO13
      mode: OUTPUT
      inverted: True
    restore_mode: ALWAYS_OFF
