substitutions:
  name: "flexboss21"
  friendly_name: "FlexBOSS21"
  
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  on_boot:
    priority: -10
    then:
      - logger.log: "Normal boot"
    
# Throttle writing parameters to the internal flash memory to reduce ESP memory wear / degradation
preferences:
  flash_write_interval: 15min

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
    level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
    
ota:
  - platform: esphome
    password: !secret ota_key

# Configure UART / RS485
uart:
  id: rs485_uart
  tx_pin: GPIO17
  rx_pin: GPIO4
  baud_rate: 19200
  parity: NONE
  stop_bits: 1

# Configure Modbus (which runs on top of RS485)
modbus:
  id: mb
  uart_id: rs485_uart
  flow_control_pin:
    number: GPIO32   # DE + /RE tied together
    inverted: true

modbus_controller:
  - id: inverter_1
    address: 1        # inverter_1 Modbus address
    modbus_id: mb
    update_interval: 10s

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "AC Couple Enabled"
    register_type: read
    address: 77
    bitmask: 0x80 #(bit 8)

sensor:
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV1 Voltage"
    id: Vpv1
    register_type: read
    address: 1
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV2 Voltage"
    id: Vpv2
    register_type: read
    address: 2
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV3 Voltage"
    id: Vpv3
    register_type: read
    address: 3
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery Voltage"
    id: Vbat
    register_type: read
    address: 4
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    id: raw_battery_status
    address: 5
    register_type: read
    value_type: U_WORD
    internal: true        # Hides this raw sensor from Home Assistant
    on_value:
      then:
        - lambda: |-
            // Extract values from the packed 0xHHLL word
            int raw = int(x);
            int soc_val = raw & 0xFF;        // Lower 8 bits (LL)
            int soh_val = (raw >> 8) & 0xFF; // Upper 8 bits (HH)
            
            // Push values to the template sensors
            id(SOC).publish_state(soc_val);
            id(SOH).publish_state(soh_val);

  - platform: template
    name: "Battery State of Charge"
    id: SOC
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    accuracy_decimals: 0

  - platform: template
    name: "Battery State of Health"
    id: SOH
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV1 Power"
    id: Ppv1
    register_type: read
    address: 7
    unit_of_measurement: "W"
    value_type: U_WORD
 
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV2 Power"
    id: Ppv2
    register_type: read
    address: 8
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV3 Power"
    id: Ppv3
    register_type: read
    address: 9
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery Charge"
    id: Pcharge
    register_type: read
    address: 10
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery Discharge"
    id: Pdischarge
    register_type: read
    address: 11
    unit_of_measurement: "W"
    value_type: U_WORD

    # this is Phase R or Split Phase grid voltage
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Grid Voltage"
    id: VacR
    register_type: read
    #register_count: 4
    address: 12
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

    # this is Phase S grid voltage
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "S-Phase Grid Voltage"
    id: VacS
    register_type: read
    #register_count: 4
    address: 13
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

    # this is Phase T grid voltage
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "T-Phase Grid Voltage"
    id: VacT
    register_type: read
    #register_count: 4
    address: 14
    unit_of_measurement: "V"
    accuracy_decimals: 2
    value_type: U_WORD
    filters: 
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Grid Frequency"
    id: Fac
    register_type: read
    address: 15
    unit_of_measurement: "Hz"
    accuracy_decimals: 2
    value_type: U_WORD
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Inverter Grid port Output Power"
    id: Pinv
    register_type: read
    #register_count: 6
    address: 16
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "AC Charging Rectified Power"
    id: Prec
    register_type: read
    #register_count: 6
    address: 17
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Inverter Current RMS"
    id: IinvRMS
    register_type: read
    address: 18
    unit_of_measurement: Amps
    value_type: U_WORD
    filters: 
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Power Factor"
    id: PF
    register_type: read
    #register_count: 6
    address: 19
    unit_of_measurement: "%"
    value_type: S_WORD
    filters: 
      - multiply: 0.001

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "R-Phase EPS Voltage"
    id: VepsR
    register_type: read
    address: 20
    unit_of_measurement: "V"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
       - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "S-Phase EPS Voltage"
    id: VepsS
    register_type: read
    address: 20
    unit_of_measurement: "V"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
       - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "T-Phase EPS Voltage"
    id: VepsT
    register_type: read
    address: 20
    unit_of_measurement: "V"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
       - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "EPS Port Frequency"
    id: Feps
    register_type: read
    address: 23
    unit_of_measurement: "Hz"
    accuracy_decimals: 2
    value_type: U_WORD
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "EPS Port Power"
    id: Peps
    register_type: read
    address: 24
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "EPS Apparent Power"
    id: Seps
    register_type: read
    address: 25
    unit_of_measurement: "VA"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Export power to Grid"
    id: Ptogrid
    register_type: read
    address: 26
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Import power from Grid"
    id: Ptouser
    register_type: read
    address: 27
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV1 Power Generation Today"
    id: Epv1_day
    register_type: read
    address: 28
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV2 Power Generation Today"
    id: Epv2_day
    register_type: read
    address: 29
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
  
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV3 Power Generation Today"
    id: Epv3_day
    register_type: read
    address: 30
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "On-Grid Power Generation Today"
    id: Einv_day
    register_type: read
    address: 31
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "AC charging Rectified Power Generation Today"
    id: Erec_day
    register_type: read
    address: 32
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Charged Energy Today"
    id: Echg_day
    register_type: read
    address: 33
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Discharged Energy Today"
    id: Edischg_day
    register_type: read
    address: 34
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Off-Grid Power Generation Today"
    id: Eeps_day
    register_type: read
    address: 35
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Export Energy to Grid Today"
    id: Etogrid_day
    register_type: read
    address: 36
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Import Energy from Grid Today"
    id: Etouser_day
    register_type: read
    address: 37
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Bus 1 Voltage"
    id: Vbus1
    register_type: read
    address: 38
    unit_of_measurement: "V"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
            
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Bus 2 Voltage"
    id: Vbus2
    register_type: read
    address: 39
    unit_of_measurement: "V"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV1 cumulative power generation"
    id: Epv1_all
    register_type: read
    address: 40
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV2 cumulative power generation"
    id: Epv2_all
    register_type: read
    address: 42
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "PV3 cumulative power generation"
    id: Epv3_all
    register_type: read
    address: 44
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Inverter Cumulative power generation"
    id: Einv_all
    register_type: read
    address: 46
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "AC Charging Rectified Cumulative power generation"
    id: Erec_all
    register_type: read
    address: 48
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Charge Cumulative power generation"
    id: Echg_all
    register_type: read
    address: 50
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Discharge Cumulative power generation"
    id: Edischg_all
    register_type: read
    address: 52
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Off Grid Inverter Cumulative power generation"
    id: Eeps_all
    register_type: read
    address: 54
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Export to Grid Cumulative power generation"
    id: Etogrid_all
    register_type: read
    address: 56
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Import from Grid Cumulative power generation"
    id: Etouser_all
    register_type: read
    address: 58
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Fault Codes"
    id: FaultCode
    register_type: read
    address: 60
    accuracy_decimals: 0
    value_type: U_DWORD_R

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Warning Code"
    id: WarningCode
    register_type: read
    address: 62
    accuracy_decimals: 0
    value_type: U_DWORD_R

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Internal Ring Temperature"
    id: Tinner
    register_type: read
    address: 64
    device_class: temperature
    unit_of_measurement: "C"
    value_type: S_WORD
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Radiator 1 Temperature"
    id: Tradiator1
    register_type: read
    address: 65
    device_class: temperature
    unit_of_measurement: "C"
    value_type: S_WORD
    state_class: measurement
    
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Radiator 2 Temperature"
    id: Tradiator2
    register_type: read
    address: 66
    device_class: temperature
    unit_of_measurement: "C"
    value_type: S_WORD
    state_class: measurement
    
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Battery Temperature"
    id: Tbat
    register_type: read
    address: 67
    device_class: temperature
    unit_of_measurement: "C"
    value_type: S_WORD
    state_class: measurement

 # - platform: modbus_controller
 #   modbus_controller_id: inverter_1
 #   name: "Runtime"
 #   id: RunningTime
 #   register_type: read
 #   address: 69
 #   accuracy_decimals: 0
 #   value_type: U_DWORD_R
 #   unit_of_measurement: 's'
 #   state_class: total_increasing
 #   device_class: duration

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: inverter_1
    name: "Working Mode"
    id: state
    register_type: read
    address: 0
    raw_encode: HEXBYTES     # read the 16-bit value as a 4-char hex string
    lambda: |-
      // x is the hex string, for example: "0000", "0010", "00C0".
      // Map values exactly as listed in the table; do not use bitmasking.
      if (x == "0000") return std::string("Standby");
      if (x == "0001") return std::string("Fault");
      if (x == "0002") return std::string("Programming");
      if (x == "0004") return std::string("PV On-Grid");
      if (x == "0008") return std::string("PV Charge");
      if (x == "000C") return std::string("PV Charge + On-Grid");
      if (x == "0010") return std::string("Battery On-Grid");
      if (x == "0014") return std::string("PV + Battery On-Grid");
      if (x == "0020") return std::string("AC Charge");
      if (x == "0028") return std::string("PV + AC Charge");
      if (x == "0040") return std::string("Battery Off-Grid");
      if (x == "0060") return std::string("Off-Grid + Battery Charging (AC-Coupled)");
      if (x == "0080") return std::string("PV Off-Grid (Not Recommended)");
      if (x == "0088") return std::string("PV Charge + Off-Grid");
      if (x == "00C0") return std::string("PV + Battery Off-Grid");
      // Fallback: If the code is not recognized, show the raw hex value.
      return std::string("Unknown (0x") + x + ")";


# Ethernet Controller
ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  power_pin: GPIO5
  phy_addr: 1
  clk:
    pin: GPIO0
    mode: CLK_OUT

# This is here to ensure that the LED for 'Cloud' isn't half-lit
switch:
  - platform: gpio
    name: "LED13 Forced"
    pin:
      number: GPIO13
      mode: OUTPUT
      inverted: True
    restore_mode: ALWAYS_OFF
